/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.greatit.demo.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Average value of items produced by Happiness machine in time window */
@org.apache.avro.specific.AvroGenerated
public class HappinessAverage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4524687491415968141L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HappinessAverage\",\"namespace\":\"com.greatit.demo.avro\",\"doc\":\"Average value of items produced by Happiness machine in time window\",\"fields\":[{\"name\":\"groupid\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"GroupId of a happiness item \",\"default\":null},{\"name\":\"total\",\"type\":\"double\",\"doc\":\"total amount of produced happiness by Happiness machine in time window\"},{\"name\":\"num_of_produced\",\"type\":\"long\",\"doc\":\"how many items were produced by Happiness machine in time window\"},{\"name\":\"avg_of_produced\",\"type\":\"double\",\"doc\":\"avg of produced happiness items in time window\"},{\"name\":\"datetime\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Time when last KTable operation happened\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HappinessAverage> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HappinessAverage> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HappinessAverage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HappinessAverage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HappinessAverage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HappinessAverage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HappinessAverage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HappinessAverage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HappinessAverage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** GroupId of a happiness item  */
  private java.lang.String groupid;
  /** total amount of produced happiness by Happiness machine in time window */
  private double total;
  /** how many items were produced by Happiness machine in time window */
  private long num_of_produced;
  /** avg of produced happiness items in time window */
  private double avg_of_produced;
  /** Time when last KTable operation happened */
  private java.lang.String datetime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HappinessAverage() {}

  /**
   * All-args constructor.
   * @param groupid GroupId of a happiness item 
   * @param total total amount of produced happiness by Happiness machine in time window
   * @param num_of_produced how many items were produced by Happiness machine in time window
   * @param avg_of_produced avg of produced happiness items in time window
   * @param datetime Time when last KTable operation happened
   */
  public HappinessAverage(java.lang.String groupid, java.lang.Double total, java.lang.Long num_of_produced, java.lang.Double avg_of_produced, java.lang.String datetime) {
    this.groupid = groupid;
    this.total = total;
    this.num_of_produced = num_of_produced;
    this.avg_of_produced = avg_of_produced;
    this.datetime = datetime;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return groupid;
    case 1: return total;
    case 2: return num_of_produced;
    case 3: return avg_of_produced;
    case 4: return datetime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: groupid = value$ != null ? value$.toString() : null; break;
    case 1: total = (java.lang.Double)value$; break;
    case 2: num_of_produced = (java.lang.Long)value$; break;
    case 3: avg_of_produced = (java.lang.Double)value$; break;
    case 4: datetime = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'groupid' field.
   * @return GroupId of a happiness item 
   */
  public java.lang.String getGroupid() {
    return groupid;
  }


  /**
   * Sets the value of the 'groupid' field.
   * GroupId of a happiness item 
   * @param value the value to set.
   */
  public void setGroupid(java.lang.String value) {
    this.groupid = value;
  }

  /**
   * Gets the value of the 'total' field.
   * @return total amount of produced happiness by Happiness machine in time window
   */
  public double getTotal() {
    return total;
  }


  /**
   * Sets the value of the 'total' field.
   * total amount of produced happiness by Happiness machine in time window
   * @param value the value to set.
   */
  public void setTotal(double value) {
    this.total = value;
  }

  /**
   * Gets the value of the 'num_of_produced' field.
   * @return how many items were produced by Happiness machine in time window
   */
  public long getNumOfProduced() {
    return num_of_produced;
  }


  /**
   * Sets the value of the 'num_of_produced' field.
   * how many items were produced by Happiness machine in time window
   * @param value the value to set.
   */
  public void setNumOfProduced(long value) {
    this.num_of_produced = value;
  }

  /**
   * Gets the value of the 'avg_of_produced' field.
   * @return avg of produced happiness items in time window
   */
  public double getAvgOfProduced() {
    return avg_of_produced;
  }


  /**
   * Sets the value of the 'avg_of_produced' field.
   * avg of produced happiness items in time window
   * @param value the value to set.
   */
  public void setAvgOfProduced(double value) {
    this.avg_of_produced = value;
  }

  /**
   * Gets the value of the 'datetime' field.
   * @return Time when last KTable operation happened
   */
  public java.lang.String getDatetime() {
    return datetime;
  }


  /**
   * Sets the value of the 'datetime' field.
   * Time when last KTable operation happened
   * @param value the value to set.
   */
  public void setDatetime(java.lang.String value) {
    this.datetime = value;
  }

  /**
   * Creates a new HappinessAverage RecordBuilder.
   * @return A new HappinessAverage RecordBuilder
   */
  public static com.greatit.demo.avro.HappinessAverage.Builder newBuilder() {
    return new com.greatit.demo.avro.HappinessAverage.Builder();
  }

  /**
   * Creates a new HappinessAverage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HappinessAverage RecordBuilder
   */
  public static com.greatit.demo.avro.HappinessAverage.Builder newBuilder(com.greatit.demo.avro.HappinessAverage.Builder other) {
    if (other == null) {
      return new com.greatit.demo.avro.HappinessAverage.Builder();
    } else {
      return new com.greatit.demo.avro.HappinessAverage.Builder(other);
    }
  }

  /**
   * Creates a new HappinessAverage RecordBuilder by copying an existing HappinessAverage instance.
   * @param other The existing instance to copy.
   * @return A new HappinessAverage RecordBuilder
   */
  public static com.greatit.demo.avro.HappinessAverage.Builder newBuilder(com.greatit.demo.avro.HappinessAverage other) {
    if (other == null) {
      return new com.greatit.demo.avro.HappinessAverage.Builder();
    } else {
      return new com.greatit.demo.avro.HappinessAverage.Builder(other);
    }
  }

  /**
   * RecordBuilder for HappinessAverage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HappinessAverage>
    implements org.apache.avro.data.RecordBuilder<HappinessAverage> {

    /** GroupId of a happiness item  */
    private java.lang.String groupid;
    /** total amount of produced happiness by Happiness machine in time window */
    private double total;
    /** how many items were produced by Happiness machine in time window */
    private long num_of_produced;
    /** avg of produced happiness items in time window */
    private double avg_of_produced;
    /** Time when last KTable operation happened */
    private java.lang.String datetime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.greatit.demo.avro.HappinessAverage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.groupid)) {
        this.groupid = data().deepCopy(fields()[0].schema(), other.groupid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.total)) {
        this.total = data().deepCopy(fields()[1].schema(), other.total);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.num_of_produced)) {
        this.num_of_produced = data().deepCopy(fields()[2].schema(), other.num_of_produced);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.avg_of_produced)) {
        this.avg_of_produced = data().deepCopy(fields()[3].schema(), other.avg_of_produced);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.datetime)) {
        this.datetime = data().deepCopy(fields()[4].schema(), other.datetime);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing HappinessAverage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.greatit.demo.avro.HappinessAverage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.groupid)) {
        this.groupid = data().deepCopy(fields()[0].schema(), other.groupid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.total)) {
        this.total = data().deepCopy(fields()[1].schema(), other.total);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.num_of_produced)) {
        this.num_of_produced = data().deepCopy(fields()[2].schema(), other.num_of_produced);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.avg_of_produced)) {
        this.avg_of_produced = data().deepCopy(fields()[3].schema(), other.avg_of_produced);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.datetime)) {
        this.datetime = data().deepCopy(fields()[4].schema(), other.datetime);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'groupid' field.
      * GroupId of a happiness item 
      * @return The value.
      */
    public java.lang.String getGroupid() {
      return groupid;
    }


    /**
      * Sets the value of the 'groupid' field.
      * GroupId of a happiness item 
      * @param value The value of 'groupid'.
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder setGroupid(java.lang.String value) {
      validate(fields()[0], value);
      this.groupid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'groupid' field has been set.
      * GroupId of a happiness item 
      * @return True if the 'groupid' field has been set, false otherwise.
      */
    public boolean hasGroupid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'groupid' field.
      * GroupId of a happiness item 
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder clearGroupid() {
      groupid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'total' field.
      * total amount of produced happiness by Happiness machine in time window
      * @return The value.
      */
    public double getTotal() {
      return total;
    }


    /**
      * Sets the value of the 'total' field.
      * total amount of produced happiness by Happiness machine in time window
      * @param value The value of 'total'.
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder setTotal(double value) {
      validate(fields()[1], value);
      this.total = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'total' field has been set.
      * total amount of produced happiness by Happiness machine in time window
      * @return True if the 'total' field has been set, false otherwise.
      */
    public boolean hasTotal() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'total' field.
      * total amount of produced happiness by Happiness machine in time window
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder clearTotal() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_of_produced' field.
      * how many items were produced by Happiness machine in time window
      * @return The value.
      */
    public long getNumOfProduced() {
      return num_of_produced;
    }


    /**
      * Sets the value of the 'num_of_produced' field.
      * how many items were produced by Happiness machine in time window
      * @param value The value of 'num_of_produced'.
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder setNumOfProduced(long value) {
      validate(fields()[2], value);
      this.num_of_produced = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'num_of_produced' field has been set.
      * how many items were produced by Happiness machine in time window
      * @return True if the 'num_of_produced' field has been set, false otherwise.
      */
    public boolean hasNumOfProduced() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'num_of_produced' field.
      * how many items were produced by Happiness machine in time window
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder clearNumOfProduced() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'avg_of_produced' field.
      * avg of produced happiness items in time window
      * @return The value.
      */
    public double getAvgOfProduced() {
      return avg_of_produced;
    }


    /**
      * Sets the value of the 'avg_of_produced' field.
      * avg of produced happiness items in time window
      * @param value The value of 'avg_of_produced'.
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder setAvgOfProduced(double value) {
      validate(fields()[3], value);
      this.avg_of_produced = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'avg_of_produced' field has been set.
      * avg of produced happiness items in time window
      * @return True if the 'avg_of_produced' field has been set, false otherwise.
      */
    public boolean hasAvgOfProduced() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'avg_of_produced' field.
      * avg of produced happiness items in time window
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder clearAvgOfProduced() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'datetime' field.
      * Time when last KTable operation happened
      * @return The value.
      */
    public java.lang.String getDatetime() {
      return datetime;
    }


    /**
      * Sets the value of the 'datetime' field.
      * Time when last KTable operation happened
      * @param value The value of 'datetime'.
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder setDatetime(java.lang.String value) {
      validate(fields()[4], value);
      this.datetime = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'datetime' field has been set.
      * Time when last KTable operation happened
      * @return True if the 'datetime' field has been set, false otherwise.
      */
    public boolean hasDatetime() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'datetime' field.
      * Time when last KTable operation happened
      * @return This builder.
      */
    public com.greatit.demo.avro.HappinessAverage.Builder clearDatetime() {
      datetime = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HappinessAverage build() {
      try {
        HappinessAverage record = new HappinessAverage();
        record.groupid = fieldSetFlags()[0] ? this.groupid : (java.lang.String) defaultValue(fields()[0]);
        record.total = fieldSetFlags()[1] ? this.total : (java.lang.Double) defaultValue(fields()[1]);
        record.num_of_produced = fieldSetFlags()[2] ? this.num_of_produced : (java.lang.Long) defaultValue(fields()[2]);
        record.avg_of_produced = fieldSetFlags()[3] ? this.avg_of_produced : (java.lang.Double) defaultValue(fields()[3]);
        record.datetime = fieldSetFlags()[4] ? this.datetime : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HappinessAverage>
    WRITER$ = (org.apache.avro.io.DatumWriter<HappinessAverage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HappinessAverage>
    READER$ = (org.apache.avro.io.DatumReader<HappinessAverage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.groupid == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.groupid);
    }

    out.writeDouble(this.total);

    out.writeLong(this.num_of_produced);

    out.writeDouble(this.avg_of_produced);

    if (this.datetime == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.datetime);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.groupid = null;
      } else {
        this.groupid = in.readString();
      }

      this.total = in.readDouble();

      this.num_of_produced = in.readLong();

      this.avg_of_produced = in.readDouble();

      if (in.readIndex() != 1) {
        in.readNull();
        this.datetime = null;
      } else {
        this.datetime = in.readString();
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.groupid = null;
          } else {
            this.groupid = in.readString();
          }
          break;

        case 1:
          this.total = in.readDouble();
          break;

        case 2:
          this.num_of_produced = in.readLong();
          break;

        case 3:
          this.avg_of_produced = in.readDouble();
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.datetime = null;
          } else {
            this.datetime = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










